### ISSUE TITLE
Lens Creation

### ISSUE THREAD

**Issue by varon** [xyncro/aether#12]
Is there any additional documentation on defining lenses?

is it possible to automatically create them for a given record, or do we need to manually define them in long-hand for each field?

Would it be possible to include this in the documentation directly?

**Comment by kolektiv** [comment]
The documentation is lacking right now, and needs to be better I agree. It isn't currently possible to automatically create lenses (as it is in Haskell for example) which is a shame. I had ideas around type providers to do so, but it's impractical to say the least. For now, it is sadly a case of writing them by hand (annoying, although at least only needing to be done once per type).

I'll try and get something documented around that, although this week might be slightly pressured for time.

Thanks for reminding me of the need for this :)

**Comment by varon** [comment]
Thanks for the prompt response.

I'll probably submit a PR with some basic docs.

**Comment by kolektiv** [comment]
Oh that would be great! That would be very much welcomed, even just a good readme with examples and basics would probably be enough for a fairly small library.

**Comment by varon** [comment]
Perhaps we should close this issue - the question has been answered and documentation has been added?

**Comment by kolektiv** [comment]
Absolutely - happy to close now as things are now better - thanks to your help! Cheers :)
