### ISSUE TITLE
Nuget package for .Net 3.5

### ISSUE THREAD

**Issue by varon** [xyncro/aether#14]
Having support for Aether on the .Net 3.5 platform would be very useful.

I've tested the compilation and that works correctly, but it seems as though Aether does not provide a Nuget package for this version.

**Comment by varon** [comment]
Any updates or progress with this?

I'd like to give this a bash, but it's going to require some quite significant build-time changes.

I'll start moving to a Paket based build instead of NuGet directly, but please advise me if this is not desirable for some or other reason.

**Comment by kolektiv** [comment]
Hi @varon - what sort of build time changes are you seeing to be needed? I'm happy to receive a pull request on this - if we can make the lib more accessible without losing functionality I'm completely open to doing that.

My initial thought was just changing the build target in the proj and then changing the folder target in the build might be enough, but I haven't thought about it too carefully! If I can help let me know.

Cheers!

**Comment by varon** [comment]
My understanding might not be perfect, but here's my take on it:

.Net 3.5 and .Net 4.* are major version differences - they require separate DLLs.
Because of this, we need to define two compilation targets and have the NuGet package include both versions after running the build for each of them.

This is possible, but somewhat clunky to do with NuGet directly from Fake, while Paket can simplify the process somewhat.

Paket itself seems to be the *de facto* standard within the F# community, so the PR would shoot two birds with one stone: move to packet, and use it to provide a 3.5 build.

**Comment by varon** [comment]
For clarity, I should add that I'm referring to using the Fake.Paket, rather than the `NuGet` functions directly.

**Comment by kolektiv** [comment]
That sounds reasonable, and I'd be perfectly happy to switch to the Paket functions - they simply didn't exist a while ago, but now they do I'd welcome them. If you can get it building happily that would be great. I use Paket for most things, the only NuGet legacies left are where time or functionality mean they haven't gone yet!

Sounds good :)

**Comment by varon** [comment]
I've made some great progress in adapting Aether to the F# project scaffold, which includes paket-based and cross-platform building. Unfortunately I've run into a minor difficulty with trying to get multiple .net dlls into one NuGet package, which I've explained in the [FAKE Gitter chat](https://gitter.im/fsharp/FAKE?at=559c03061c1634674f8a6fb9). 

If you have any ideas on this, please do let me know. For tomorrow, I'll keep trying various configurations until something sticks.

**Comment by varon** [comment]
I've opened up an issue requesting more documentation on how to achieve this with FAKE's Paket module. You can find this here:  https://github.com/fsharp/FAKE/issues/861

**Comment by kolektiv** [comment]
I'm going to close this one as I think the spirit of the issue has been fulfilled, even if not the letter! :) Do feel free to re-open though if there's something here I've missed that you need...
