### ISSUE TITLE
Convention for lens declarations

### ISSUE THREAD

**Issue by varon** [xyncro/aether#15]
Is there any convention for declaring lenses?

Considering the following example:

```fsharp
type Foo = 
    { aValue : int
      bValue : int }
      
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Foo =
    module Lens =
        let aValue:Lens<_,_> =  (fun foo -> foo.aValue), (fun aValue x -> { x with aValue = aValue })
        let bValue:Lens<_,_> =  (fun foo -> foo.bValue), (fun bValue x -> { x with bValue = bValue })
```

Several questions arise:
 1. Do we want to put the lenses into a `Lens` submodule?
 1. Do we suffix them with 'Lens'? (I've seen `aValue_` in the `Foo` module before, but that seems a bit opaque.)
 1. Do we use the shorthand `v` and `x` ? (The names are hidden as they're lambdas anyway the `Lens<_,_>`)

Having some conventions here might make these more discoverable, at least until they're introduced as a first class language feature.

**Comment by varon** [comment]
@kolektiv Any feedback on this?

**Comment by kolektiv** [comment]
I've tended, when implementing lenses on types, to add them as static members of that type. That's not totally satisfying though, as lenses that you then compose live as simple let bindings, and so you have two different places. It's tricky with F# naming standards/conventions to provide the right choice.

I've tended to settle on static type members for the lens components, which are as accessible as the type, and the composed lenses as let declarations as they tend to be local and private or internal.

The Haskell convention of underscores I actually like, but it's not very F# like (I've reluctantly tried to be fairly mainstream!)

I've also always just used `x` as a variable in the lenses, and the first letter of the field for the value, in the case of records.

The only convention i've also got is suffixing the lenses (whether static type members or let declarations) with Lens or PLens. It's a bit verbose, but seemed sensible enough.

There is an argument that the few existing lenses provided (`mapPLens` etc.) should probably be renamed to something like `Map.keyPLens` or something similar. Opinions welcome!

**Comment by varon** [comment]
Perhaps @dsyme might have some input here?

**Comment by dsyme** [comment]
http://suave.io has conventions for declaring functional properties as first class values which I'd encourage you to follow.  See

https://github.com/SuaveIO/suave/blob/cc8ea78df964d10c6d2820ae6074a9432283a7d9/src/Suave/Utils/Collections.fs#L37

https://github.com/SuaveIO/suave/blob/cc8ea78df964d10c6d2820ae6074a9432283a7d9/src/Suave/Sockets/SocketBinding.fs#L23

**Comment by kolektiv** [comment]
That's interesting, the underscore suffix seems counter to expectation!
Having an underscore suffixed property for a lens may be worthwhile.

I think the difficult one is the composition of multiple lenses, where the
resultant composition isn't specific to a single type. That can only really
be a let decl, but whether it should perhaps be placed in a suitably named
module with [<RequireQualifiedAccess>] is open to debate. Possibly yes, if
they're not private or otherwise locally scoped.

**Comment by dsyme** [comment]
@kolektiv - Correct, I don't have any specific guidelines about where to locate compositions - my main first concern is to get some regularity with nominal type design.

**Comment by kolektiv** [comment]
I think we're roughly OK with the basics there, so we have type definitions
in a similar sense to Suave:

https://github.com/xyncro/aether/blob/master/src/Aether/Aether.fs#L11-L22

However, there's an argument that we should move these lenses in to a set
of suitable namespaces:

https://github.com/xyncro/aether/blob/master/src/Aether/Aether.fs#L119-L147

In terms of the lenses as part of types themselves, our current approach is
static members, so a record with field `MyField` will have a lens something
like `static member MyFieldLens =`... (Or `MyFieldPLens` for a partial
lens). Does that seem sane, or would a convention with different
casing/underscores/other be better?

Compositions are just tricky, I'm not sure there's a solution to that which
will fit with common F# convention right now, as we don't tend to use
"naked" declarations as much as e.g. Haskell...

**Comment by varon** [comment]
The underscore is certainly much terser; even if it's not immediately obvious, I'd prefer that as it will cut down on boilerplate.

I've noticed that you're referring to lenses as functional properties.

Is this a term you want to standardize in F#? To what extent would you be behind renaming Aether's Lenses to Properties?

I do greatly prefer the name Lens for two reasons:
  1. It differentiates significantly from traditional properties which do actually exist in F# as well.
  1. It has a clear meaning in the context of functional programming.

I suspect if we called them Lenses, all we'd really need would be an article on http://fsharpforfunandprofit.com/ or similar to get the community familiar with the naming of the concept.

They're incredibly powerful, and I'd like eventually like to see them as a first class language feature.

**Comment by dsyme** [comment]
Yes, I'm not 100% committed to the "Lens" terminology - I don't mind it but for Suave I think it would have been a needles conceptual barrier of entry.  I do feel that the terminology "functional property" is entirely natural and needs no explanation.  

I don't mind it if beginners later discover a Lens framework and the first thing they read is "functional properties are just very simple lenses, now lets compose them".

So my preference for an F# property ``P`` is to use ``P_`` with type ``Property<'T,'P>``, using a type equivalence to a tuple of functions precisely as in Suave.  The use of a type equivalence means that they will be compatible with a Lens framework and terminology.

**Comment by varon** [comment]
Thanks for the clear explanation, Don.

If we define Functional Property as a special kind of lens it's going to be pretty easy to tell people new to Aether that "functional properties = total lenses".

I'll try to draft up some documentation on standards for ~~lens~~ functional property declarations as a PR, based on your guidelines.

**Comment by kolektiv** [comment]
I have to admit to some level of nervousness about that, as I'm not totally sure it covers all the cases. In terms of syntax, a property P having a lens P_ where P_ is a total lens is ok, but do we have an equivalent for a partial lens? Can we cater for that in conventions?

Saying that all lenses are properties might be pushing it as well - lenses for head and tail of a list for example might stretch that definition (although I suppose List does have Head and Tail instance properties - the lenses would be partial however). Lenses as a family of topics would also cover morphisms and partial morphisms (prisms) which we have, but wouldn't have a syntactical convention for.

I wonder whether calling a specific subset of a thing "functional properties" might cause more confusion in the long run? Just thinking out loud, and am certainly capable of seeing other viewpoints!

**Comment by varon** [comment]
I think it's good that you're concerned with terminological accuracy, @kolektiv. However, I do think we need to consider the typical users of Aether versus F# as a whole.

Don is trying to make things simple and clear to beginner F# programmers.The idea of 'functional properties' is readily understandable to anyone who knows C# properties or traditional getter/setter method pairs.

I could be overestimating the complexity, but it strikes me that Aether is probably not a library that's going to be used beginners in F#.

Given that Aether is aimed at more advanced FP users, it seems perfectly fine for Aether to define itself as a lens library. We can get the best of both worlds by clearly indicating in the documentation the relation between functional properties and the more general concept of lenses.

I don't think we need to be overly concerned with syntactic conventions for partial lenses and isomorphisms. While I'm open to proposals on that, I suspect their usage will be vastly less common than functional properties.

**Comment by varon** [comment]
I've spotted a potential problem with the static member approach as outlined:

```fsharp
open System
open System.Diagnostics

type Foo = 
    { someField : string }
    static member someField_ = (fun x -> x.someField), (fun v x -> { x with someField = v })

module FooModule = 
    let someField_ = (fun x -> x.someField), (fun v x -> { x with someField = v })

let benchmark msg f = 
    let sw = Stopwatch()
    sw.Start()
    for i = 0 to 10000000 do
        f()
    sw.Stop()
    printfn "%s took: %d" msg sw.ElapsedMilliseconds

[<EntryPoint>]
let main _ = 
    let foo = { someField = "value" }
    let useModule() = fst FooModule.someField_ foo |> ignore
    benchmark "module function" useModule
    let useMember() = fst Foo.someField_ foo |> ignore
    benchmark "static member" useMember
    Console.Read() |> ignore
    0
```
On Windows using .net 4.5.1, I get the following output:
```
module function took: 237
static member took: 488
```
As you can see, there's a not-insignificant performance difference between these.

The reason this occurs is because static members are evaluated each time, while module let bindings are not.

Factoring in GC in addition to the overhead, it seems like it's going to be quite a bit less efficient compared to the module-level let bindings.

**Comment by dsyme** [comment]
I don't mind the use of a Foo module, it's more the naming I'm interested in.  Ideally the performance would be just as good in either case though, it would be nice to see an F# compiler optimization to make that so.

**Comment by varon** [comment]
Based on what we've discussed so far, I'd like to propose the following as conventions for Aether, and beyond that, for a possible PR to the component design guidelines:

Normal F# code:
```fsharp
// These should probably be included in F# core.
type Property<'T, 'P> = ('T -> 'P) * ('P -> 'T -> 'T)
let Property<'T, 'P> getter setter : Property<'T, 'P> = (getter, setter)
    
type Foo = 
    { someField : string
      anotherField : string }

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Foo = 
    let someField_ = Property (fun x -> x.someField) (fun v x -> { x with someField = v })
    let anotherField_ = Property (fun x -> x.anotherField) (fun v x -> { x with anotherField = v })
```
In this case, someField_ will have the type `Property<Foo,string>`.
This is type equivalent to `(Foo -> string) * (string -> Foo -> Foo)`

-----

And if you're using Aether:

```fsharp
// These should be included in the Aether namespace.
type Lens<'T, 'P> = Property<'T, 'P>
let Lens<'T, 'P> getter setter : Lens<'T, 'P> = (getter, setter)
    
type Foo' = 
    { someField : string
      anotherField : string }

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Foo' = 
    let someField_ = Lens (fun x -> x.someField) (fun v x -> { x with someField = v })
    let anotherField_ = Lens (fun x -> x.anotherField) (fun v x -> { x with anotherField = v })
```
In this case, someField_ will have the type `Lens<Foo,string>`.
This is type equivalent to `(Foo -> string) * (string -> Foo -> Foo)`

-----
Doing it this way should give us the best of both worlds - we have a simple way way to declare functional properties which actual Aether lens declarations would match in both name and type (through type equivalence).

**Comment by kolektiv** [comment]
In terms of the broader picture, I can see the sense in defining a `Property<'a,'b>` type (I don't know what the criteria for getting something like that in to FSharp.Core is though).

The convention in terms of a module seems reasonable, although I would like to suggest that in the Aether case it's considered equally valid to have a static type member despite the performance. This is because lenses are most useful in cases with a complex type hierarchy, each of which exposes lenses. If we're saying that each type would need an equivalent module, that would be extremely verbose. Making it so that both approaches are valid seems reasonable given that (opinions welcome). A Property always being `<Type Name/Matching Module Name>.<Property Name>_` seems ok to me, I think.

However, it leaves a few questions around Aether, as we obviously have more than just properties, and it would be nice to have conventions which could cope with that. Partial lenses (or partial properties), in many cases, actually turn out to be far more common than total ones in many of the cases I've been working with, so covering that case seems sensible.

About all I can think of is the following options for partials:
a) No difference. They also have a trailing underscore. Problematic if you want to provide both a partial and total lens though.
b) Double underscore. Haven't actually tested if that's valid! Might work? Maybe a bit of a slippery slope...

Also there's Isomorphisms (total and partial). Not sure about these. We don't really have enough special chars to play with! Any thoughts?

Underscore and double underscore may work for total and partial lenses/properties though.

**Comment by kolektiv** [comment]
Incidentally, type equivalence was always the point. The lenses defined in Suave are that way so they are the same as Aether, as Aether was always about being able to use things via type equivalence, so that library authors could avoid dependencies.

**Comment by kolektiv** [comment]
As an example, incidentally, of where "module per type" for lenses would be awkward, consider the Arachne URI type, which will be gaining lenses to enable lens based functionality right down in to the depths of the type.

https://github.com/freya-fs/arachne/blob/master/src/Arachne.Uri/Uri.fs#L614-L615

**Comment by varon** [comment]
The name based approach is probably best. Allowing static members or module types would allow greater flexibility. I'll factor that in when I do the documentation updates.

I think the applicability of Total vs Partial lenses depends heavily on the domain.
In my case, I have zero usages of partial lenses because I'm working with extremely reliable and well constructed data. Either way, we definitely want to handle both cases.

I think the double underscore approach isn't great - it's not easily distinguishable from normal lenses, nor is it clear to someone new how the two are different.

I'd suggest something like `someValue_p` or `someValue_par` for partial lenses. This approach should be extensible to other types of lenses, too.

**Comment by dsyme** [comment]
@varon Yes, the guidelines can allow either a static member or module.

Is there any specific reason that partial lenses would need to have a ``_p`` suffix - could they just use ``_`` as well, with a different type?

**Comment by varon** [comment]
My motivation for the `_p` suffix was fairly simple - I had anticipated very opaque type errors due to the tuple-based types, which the suffix might have helped demystify. I was wrong here - as long as we declare our lenses with the proper types, we get very readable type errors.

For instance, if we try to compose a partial lens of `Bar -> Foo option` and a `Foo -> string`, we receive the following error:

```
Error	1	Type mismatch. Expecting a
    Lens<Bar,Foo option>    
but given a
    PLens<Bar,Foo>    
The type 'Foo option' does not match the type 'Foo'
```

However, to get these clear types, I did have to declare lenses using the following helper functions:

```fsharp
let Lens<'T, 'P> getter setter : Lens<'T, 'P> = (getter, setter)
let PLens<'T, 'P> getter setter : PLens<'T, 'P> = (getter, setter)
```

With the actual declarations as:
```fsharp
// partial lens from Bar -> Foo option
let foo_ = PLens (fun x -> x.foo) (fun v x -> {x with foo = Some v})
// total lens from Foo -> string
let someField_ = Lens (fun x -> x.someField) (fun v x -> { x with someField = v })
```

if we don't have the helper functions, things become a bit less clear:

```fsharp
let foo_ = (fun x -> x.foo), (fun v x -> {x with foo = Some v})
```

```
Error	1	Type mismatch. Expecting a
    Lens<Bar,Foo option>    
but given a
    (Bar -> Foo option) * (Foo -> Bar -> Bar)
```

You can view the full example here: https://gist.github.com/varon/59dba8cd9a554cccbd49

If we can exclusively use the helper functions for declaring lenses, I think the single underscore works fine for both types of lenses.

How do you suggest we resolve the naming for isomorphisms?

**Comment by kolektiv** [comment]
The error messages are certainly clearer when it can be inferred that your lenses or partial lenses are a particular type, rather than simply a coincidental tuple. However, that then requires a particular dependency on a common type, thus losing some of the benefit of relying on type equivalence. You can avoid the helper functions by simply declaring your lenses to be of type lens (i.e. `static member Property_ : Lens<Ty,Prop> = ...`) but again, you've now got a concrete dependency on some `Lens<'a,'b>` type.

The other aspect to distinguishing partial and total comes from the fact that I've sometimes wished to declare both. For example, I have lenses `mapKeyLens k` and `mapKeyPLens k` which are both lenses to a particular key in a map. The first will throw if the key is not present (equiv to find), the second is partial (equiv to tryFind). Without something to distinguish, these would be the same name, obviously not possible.

Isomorphisms (/prisms) could again do with something. Currently they have the suffix Iso or PIso, but this doesn't quite fit if lenses use underscore suffixing.

I have to admit I haven't come up with anything better, which is why the convention has been as it is, in my own code! But definitely happy to hear a better suggestion.

**Comment by varon** [comment]
@kolektiv What percentage of lens declarations do you estimate would have conflicting total/partial lenses on the same type?

I don't anticipate it to be incredibly common, so how do you feel about going with `_` unless there's a conflict, then go with `_p`, `_i` and `_pi` ?

I've also noticed another issue with the `Lens<'T, 'P> getter setter : Lens<'T, 'P> = (getter, setter)` helper function - it seems to prevent calling `Lens.Map`, as the `Lens` part resolves to the helper function, rather than the Lens module itself. Perhaps lower-casing it as `lens` would be better, if we're going to use such as thing.

**Comment by dsyme** [comment]
My recommendation is to just use an underscore for both partial and total properties-as-first-class values.

|  but again, you've now got a concrete dependency on some  ``Lens<'a,'b>``  type.

It's not a binary/concrete dependency If the type definition is a type abbreviation, though each library defining the Lens/Property and PLens/PartialProprerty abreviations much agree on shape of the definitions.

**Comment by kolektiv** [comment]
So, having slept on this (10 times, to be fair) I'm inclined to go with the underscore convention for now. It seems reasonable, and we'll address the error checking aspects down the line if they prove problematic. I'm still not sure quite how to address that while still being able to rely on type equivalence for implementation, but let's see how it works in practice.

**Comment by kolektiv** [comment]
This has now been implemented pretty much everywhere I'm aware of, so closing as done!
