### ISSUE TITLE
Make Aether a portable library

### ISSUE THREAD

**Issue by neoeinstein** [xyncro/aether#33]
Per the advice given in a recent [keynote by the Visual F# team](https://skillsmatter.com/skillscasts/7076-keynote-the-past-present-and-future-of-visual-f-sharp), we should look at providing Aether (and Chiron) as portable libraries that can be consumed on .NET Core as well.

**Comment by neoeinstein** [comment]
Cross reference to xyncro/chiron#59

**Comment by kolektiv** [comment]
https://github.com/fsprojects/FsProjectsAdmin/issues/10 for reference...

**Comment by kolektiv** [comment]
https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/42 for reference...

**Comment by kolektiv** [comment]
8.0.2 is now a portable library! Profile259. 8.0.1 is as well, but just... ever so slightly imperfect :)
