### ISSUE TITLE
Lenses on Generic Records

### ISSUE THREAD

**Issue by varon** [xyncro/aether#37]
Are there any suggested practices for declaring lenses on generic records?
```fsharp
type Record<'a> = 
    { Data : 'a }
    static member data_ = (fun x -> x.Data), (fun v x -> { x with Data = v })
```
In this case, `data_` is inferred to have type `(Record<obj> -> obj) * (obj -> Record<obj> -> Record<obj>)` aka `Lens<Record<obj>, obj>`.

Placing it as a module function without any explicit types sort of works:
```fsharp
module Record =
    let data_ = (fun x -> x.Data), (fun v x -> { x with Data = v })
```
but it infers a too general type of `(Record<'a> -> 'a) * ('b -> Record<'b> -> Record<'b>)` rather than the lens type of `(Record<'a> -> 'a) * ('a -> Record<'a> -> Record<'a>)`.

It's possible to explicitly provide the types:
```fsharp
type Record<'a> = 
    { Data : 'a }
    static member data_: Lens<Record<'a>,'a> = (fun x -> x.Data), (fun v x -> { x with Data = v })
```

But obviously with longer signatures inside records this becomes incredibly unwieldy, as per this example from my own project:
```fsharp
let properties_ : Lens<StructureDescription<'a>, (string * Parser<'a -> 'a, unit>) list> = (fun x -> x.properties), (fun v x -> { x with properties = v })
```

What's the best way of declaring these?

**Comment by kolektiv** [comment]
Hmmm, I haven't got any magic trick there, I tend to just have a few more line breaks. So for example, I'd write the record and lens above as:

```fsharp
type Record<'a> = 
    { Data : 'a }

    static member data_ : Lens<Record<'a>,'a> =
        (fun x -> x.Data), (fun v x -> { x with Data = v })
```

And potentially (when the individual getters and setters start also getting verbose) as:


```fsharp
type Record<'a> = 
    { Data : 'a }

    static member data_ : Lens<Record<'a>,'a> =
        (fun x -> x.Data),
        (fun v x -> { x with Data = v })
```

Obviously that's not any more minimal, but I've found it readable. One of those two options tends to be my general rule.

**Comment by kolektiv** [comment]
To add as well, I would only generally annotate in terms of types where needed - in this case it does matter due to the generic type of course.

**Comment by varon** [comment]
Yeah. I usually use a helper function to declare them with a nice type:
```fsharp
let inline lens<'a, 'b> get set : Lens<'a, 'b> = (get, set)
```
Unfortunately it's not compatible with generic records, so I've omitted their usage in this example.

**Comment by kolektiv** [comment]
Yes - generic records seem like they're likely to remain an irritating edge case I think, in the absence of any major changes to F#. It does work as it is, but as you say, it can be more verbose than we'd like, sadly. I've always ended up aiming at the most readable short-lines layout, and going with that.

**Comment by varon** [comment]
Thanks for your insight on this.

I'd reckon that adding this to the usage guide would be helpful. It's definitely worth making it explicit that users will need to handle the generic records differently.

**Comment by kolektiv** [comment]
Yes you're right. https://github.com/xyncro/sites-xyncro.tech/issues/1 - I'll look at that, it's a guide I'd planned to write, and this reminds me!

**Comment by varon** [comment]
Well, with that, I think we can consider this resolved. Thank you for your prompt responses and really useful library!

**Comment by kolektiv** [comment]
No problem at all - I'm always happy when people find things useful! More issues and thoughts will always be welcome. :)
