### ISSUE TITLE
Setting a key in a map doesn't add the key if it isn't already there

### ISSUE THREAD

**Issue by mavnn** [xyncro/aether#42]
Looking at the code ( https://github.com/xyncro/aether/blob/master/src/Aether/Aether.fs#L435 ) this appears to be deliberate, but it seems unexpected. What's the rationale?

**Comment by kolektiv** [comment]
Yes, to obey the lens laws suitably, there are two implementations, both of which maintain the logical "shape" of the data structure. So `key_` will not modify a key that does not already exist. The alternative, `value_` treats values as options, so a value which does not exist is `None`, which does exist is `Some` etc.

You'll often find that if you want to be adding values to a map, `value_` is more useful and explicit.

**Comment by mavnn** [comment]
Fair. I'll let this rest here for other people's curiosity to be satisfied.
